/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package distributeddatabase;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javafx.scene.input.KeyCode.O;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JTable;


/**
 *
 * @author Asus
 */
public final class S_F_Donorlist extends javax.swing.JFrame {
    String blood;

    

    /**
     * Creates new form S_F_Donorlist
     */
    public S_F_Donorlist() {
        initComponents();
        showDisplay();
        //initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
     DefaultTableModel model;
    Object[] row;
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Blood Group");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Submit");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Back Menu");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "ID", "Blood Group", "Medical Report", "Address", "Phone Number"
            }
        ));
        jScrollPane4.setViewportView(jTable3);

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rashed", "Mahatab", "Giti", "Noor" }));
        jComboBox1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Again Search");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 24, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 982, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(244, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
          menu m = new menu();
       m.show();
       this.hide();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
      /* blood= jTextField1.getText();
        System.out.println(blood);
        
        if(blood.equals("") || blood == null){
              model = (DefaultTableModel) jTable3.getModel();
              column = new Object[6];
             JOptionPane.showMessageDialog(this,"Please Enter A Valid Blood group");
         }
         else
         {
            try {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","D","66586");
            
            Statement st= con.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM DONORLIST WHERE BLOOD_GROUP='"+blood+"'");
            //ResultSet rs = c.createStatement().executeQuery(SQL);
            //while(rs.next())
            //{
            //System.out.println(rs.getString(1));
            //}
                
            //int i=1,j=2,k=3,l=4;
           
            while(rs.next())
            {
                    column[0] = rs.getString("NAME");
                    column[1] = rs.getString("DONOR_ID");
                    column[2] = rs.getString("BLOOD_GROUP");
                    column[3] = rs.getString("MEDICAL_REPORT");
                    column[4] = rs.getString("DONOR_ADDRESS");
                    column[5] = rs.getString("DONOR_NUMBER");
                    //column.add(rs.getString("NAME"));
 
                    
                   // System.out.println(rs.getString("NAME"));
                   model.addRow(column);
                   //Row row = new Row(column);
                    //result.getColumns().addAll(col);
            
       
                
                 jTable3.getModel();
                 //(rs.getString(i)+"----"+rs.getString(j)+"-----"+rs.getString(k)+"----"+rs.getString(l));
            }
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(S_F_Donorlist.class.getName()).log(Level.SEVERE, null, ex);
        }
         }
         
        
         */
      
      
      
      
      
      
      
      
      
      
      
      
          blood= jTextField1.getText();
         String items = jComboBox1.getSelectedItem().toString();

        if (items.equals("Rashed")) {
            model = (DefaultTableModel) jTable3.getModel();
            row = new Object[6];
            try {
                //Connection con = DBconnect.getConnection();
                
                Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","rashed","66586");
                PreparedStatement ps = con.prepareStatement("SELECT *FROM DONORLIST WHERE BLOOD_GROUP='"+blood+"'");
                jLabel2.setText("Searching finished succcessfully");
                ResultSet rs = ps.executeQuery();
                while (rs.next()) {
                    row[0] = rs.getString("NAME");
                    row[1] = rs.getString("DONOR_ID");
                    row[2] = rs.getString("BLOOD_GROUP");
                    row[3] = rs.getString("MEDICAL_REPORT");
                    row[4] = rs.getString("DONOR_ADDRESS");
                    row[5] = rs.getString("DONOR_NUMBER");
                    model.addRow(row);

                }
                con.close();

            } catch (Exception ex) {
                ex.printStackTrace();
            }
        } else if (items.equals("Mahatab")) {

            model = (DefaultTableModel) jTable3.getModel();
            row = new Object[6];
            try {
               
                Connection con=DriverManager.getConnection("jdbc:oracle:thin:@192.168.43.4:1521:XE","mahatab","12345");
                PreparedStatement ps = con.prepareStatement("SELECT *FROM DONORLIST WHERE BLOOD_GROUP='"+blood+"'");
                 jLabel2.setText("Searching finished succcessfully");
                ResultSet rs = ps.executeQuery();
                while (rs.next()) {
                    row[0] = rs.getString("NAME");
                    row[1] = rs.getString("DONOR_ID");
                    row[2] = rs.getString("BLOOD_GROUP");
                    row[3] = rs.getString("MEDICAL_REPORT");
                    row[4] = rs.getString("DONOR_ADDRESS");
                    row[5] = rs.getString("DONOR_NUMBER");;
                    model.addRow(row);

                }
                con.close();

            } catch (Exception ex) {
                ex.printStackTrace();
            }
        } 
        else if (items.equals("Giti")) {
            model = (DefaultTableModel) jTable1.getModel();
            row = new Object[6];
            try {
                Connection con=DriverManager.getConnection("jdbc:oracle:thin:@192.168.43.47:1521:XE","giti1","12345");
                PreparedStatement ps = con.prepareStatement("SELECT *FROM DONORLIST WHERE BLOOD_GROUP='"+blood+"'");
                 jLabel2.setText("Searching finished succcessfully");
                ResultSet rs = ps.executeQuery();
                while (rs.next()) {
                    row[0] = rs.getString("NAME");
                    row[1] = rs.getString("DONOR_ID");
                    row[2] = rs.getString("BLOOD_GROUP");
                    row[3] = rs.getString("MEDICAL_REPORT");
                    row[4] = rs.getString("DONOR_ADDRESS");
                    row[5] = rs.getString("DONOR_NUMBER");
                    model.addRow(row);

                }
                con.close();

            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
        else if(items.equals("Noor")) {
            model = (DefaultTableModel) jTable1.getModel();
            row = new Object[6];
            try {
                Connection con=DriverManager.getConnection("jdbc:oracle:thin:@192.168.43.224:1522:XE","mahatab","12345");
                PreparedStatement ps = con.prepareStatement("SELECT *FROM DONORLIST WHERE BLOOD_GROUP='"+blood+"'");
                 jLabel2.setText("Searching finished succcessfully");
                ResultSet rs = ps.executeQuery();
                while (rs.next()) {
                    row[0] = rs.getString("NAME");
                    row[1] = rs.getString("DONOR_ID");
                    row[2] = rs.getString("BLOOD_GROUP");
                    row[3] = rs.getString("MEDICAL_REPORT");
                    row[4] = rs.getString("DONOR_ADDRESS");
                    row[5] = rs.getString("DONOR_NUMBER");
                    model.addRow(row);

                }
                con.close();

            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }                                          

    public void showDisplay() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        
        Object[] row = new Object[6];
        try {
            //Connection con = DBconnect.getConnection();
            Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","rashed","66586");
            PreparedStatement ps = con.prepareStatement("SELECT *FROM DONORLIST WHERE BLOOD_GROUP='"+blood+"'");
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                row[0] = rs.getString("NAME");
                    row[1] = rs.getString("DONOR_ID");
                    row[2] = rs.getString("BLOOD_GROUP");
                    row[3] = rs.getString("MEDICAL_REPORT");
                    row[4] = rs.getString("DONOR_ADDRESS");
                    row[5] = rs.getString("DONOR_NUMBER");
                model.addRow(row);

            }
            con.close();

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    

       
       

           
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
          this.hide();
        S_F_Donorlist dl = new S_F_Donorlist();
        dl.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(S_F_Donorlist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(S_F_Donorlist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(S_F_Donorlist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(S_F_Donorlist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new S_F_Donorlist().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    /**
     *
     */

}
