/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package distributeddatabase;



import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javafx.scene.input.KeyCode.O;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JTable;

/**
 *
 * @author Asus
 */
public final class S_F_BLOOD_BANK extends javax.swing.JFrame {
    String blood1;

    /**
     * Creates new form S_F_BLOOD_BANK
     */
    public S_F_BLOOD_BANK() {
        initComponents();
        showDisplay();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
      DefaultTableModel model;
      Object[] row;
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Blood Group");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rashed", "Mahatab", "Giti", "Noor" }));
        jComboBox1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Submit");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Back Menu");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "B B Name", "B B Address", "BB D Name", "Donor B Group", "B B Number"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Again Search");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(75, 75, 75)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(89, 89, 89)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(105, 105, 105)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(71, 71, 71)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(161, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
          blood1= jTextField1.getText();
         String items = jComboBox1.getSelectedItem().toString();

        if (items.equals("Rashed")) {
            model = (DefaultTableModel) jTable1.getModel();
            row = new Object[5];
            try {
                //Connection con = DBconnect.getConnection();
                
                Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","rashed","66586");
                PreparedStatement ps = con.prepareStatement("SELECT * FROM DATA_OF_BLOOD_BANK WHERE DONOR_B_GROUP='"+blood1+"'");
                 jLabel2.setText("Searching finished succcessfully");
                ResultSet rs = ps.executeQuery();
                while (rs.next()) {
                    row[0] = rs.getString("BLOOD_B_NAME");
                    row[1] = rs.getString("BLOOD_B_ADDRESS");
                    row[2] = rs.getString("BLOOD_B_D_NAME");
                    row[3] = rs.getString("DONOR_B_GROUP");
                    row[4] = rs.getString("BLOOD_B_NUMBER");
                    //row[5] = rs.getString("DONOR_NUMBER");
                      model.addRow(row);

                }
                con.close();

            } catch (Exception ex) {
                ex.printStackTrace();
            }
        } else if (items.equals("Mahatab")) {

            model = (DefaultTableModel) jTable1.getModel();
            row = new Object[5];
            try {
                //Connection con = DBconnect.getConnection();
                Connection con=DriverManager.getConnection("jdbc:oracle:thin:@192.168.43.4:1521:XE","mahatab","12345");
                PreparedStatement ps = con.prepareStatement("SELECT * FROM DATA_OF_BLOOD_BANK WHERE DONOR_B_GROUP='"+blood1+"'");
                 jLabel2.setText("Searching finished succcessfully");
                ResultSet rs = ps.executeQuery();
                while (rs.next()) {
                      row[0] = rs.getString("BLOOD_B_NAME");
                    row[1] = rs.getString("BLOOD_B_ADDRESS");
                    row[2] = rs.getString("BLOOD_B_D_NAME");
                    row[3] = rs.getString("DONOR_B_GROUP");
                    row[4] = rs.getString("BLOOD_B_NUMBER");

                }
                con.close();

            } catch (Exception ex) {
                ex.printStackTrace();
            }
        } else if (items.equals("Giti")) {
            model = (DefaultTableModel) jTable1.getModel();
            row = new Object[5];
            try {
                //Connection con = DBconnect.getConnection();
                Connection con=DriverManager.getConnection("jdbc:oracle:thin:@192.168.43.47:1521:XE","giti1","12345");
                PreparedStatement ps = con.prepareStatement("SELECT * FROM DATA_OF_BLOOD_BANK WHERE DONOR_B_GROUP='"+blood1+"'");
                 jLabel2.setText("Searching finished succcessfully");
                ResultSet rs = ps.executeQuery();
                while (rs.next()) {
                      row[0] = rs.getString("BLOOD_B_NAME");
                    row[1] = rs.getString("BLOOD_B_ADDRESS");
                    row[2] = rs.getString("BLOOD_B_D_NAME");
                    row[3] = rs.getString("DONOR_B_GROUP");
                    row[4] = rs.getString("BLOOD_B_NUMBER");
                    model.addRow(row);

                }
                con.close();

            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
        else if (items.equals("Noor")) {
            model = (DefaultTableModel) jTable1.getModel();
            row = new Object[5];
            try {
                //Connection con = DBconnect.getConnection();
                Connection con=DriverManager.getConnection("jdbc:oracle:thin:@192.168.43.224:1521:XE","Noor2","12345");
                PreparedStatement ps = con.prepareStatement("SELECT * FROM DATA_OF_BLOOD_BANK WHERE DONOR_B_GROUP='"+blood1+"'");
                 jLabel2.setText("Searching finished succcessfully");
                ResultSet rs = ps.executeQuery();
                while (rs.next()) {
                      row[0] = rs.getString("BLOOD_B_NAME");
                    row[1] = rs.getString("BLOOD_B_ADDRESS");
                    row[2] = rs.getString("BLOOD_B_D_NAME");
                    row[3] = rs.getString("DONOR_B_GROUP");
                    row[4] = rs.getString("BLOOD_B_NUMBER");
                    model.addRow(row);

                }
                con.close();

            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }                                          

    public void showDisplay() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        
        Object[] row = new Object[5];
        try {
            
            Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","rashed","66586");
            PreparedStatement ps = con.prepareStatement("SELECT * FROM DATA_OF_BLOOD_BANK WHERE DONOR_B_GROUP='"+blood1+"'");
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                      row[0] = rs.getString("BLOOD_B_NAME");
                    row[1] = rs.getString("BLOOD_B_ADDRESS");
                    row[2] = rs.getString("BLOOD_B_D_NAME");
                    row[3] = rs.getString("DONOR_B_GROUP");
                    row[4] = rs.getString("BLOOD_B_NUMBER");
                model.addRow(row);

            }
            con.close();

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
          menu m = new menu();
       m.show();
       this.hide();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         this.hide();
        S_F_BLOOD_BANK dk = new S_F_BLOOD_BANK();
        dk.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(S_F_BLOOD_BANK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(S_F_BLOOD_BANK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(S_F_BLOOD_BANK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(S_F_BLOOD_BANK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new S_F_BLOOD_BANK().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
